"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# ตัวแปรนี้เป็นเหมือนโฟลเดอร์หลักของโปรเจกต์ ใช้สำหรับอ้างอิงตำแหน่งไฟล์ต่างๆ
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# กุญแจลับสำหรับเข้ารหัสความปลอดภัย (เช่น Session, CSRF Token) ห้ามหลุดเด็ดขาด
SECRET_KEY = 'django-insecure-6xejusf=(^suk@h5m@wd7mrnrq(b%)cv55d6^(#nh2kn%n&*=('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# รายชื่อแอปพลิเคชันทั้งหมดที่ติดตั้งในโปรเจกต์นี้ (ถ้าสร้าง App ใหม่ ต้องมาใส่ชื่อที่นี่)
INSTALLED_APPS = [
    'django.contrib.admin',      # ระบบหลังบ้านของ Django
    'django.contrib.auth',       # ระบบบัญชีผู้ใช้
    'django.contrib.contenttypes', # จัดการชนิดข้อมูล
    'django.contrib.sessions',   # ระบบจดจำการล็อกอิน
    'django.contrib.messages',   # ระบบแจ้งเตือน (Flash Messages)
    'django.contrib.staticfiles',# จัดการไฟล์ Static (CSS, JS)
    'tailwind',                  # (ถ้าใช้) กรอบการทำงาน CSS
    
    # Custom Apps ของเราเอง
    'accounts',      # ระบบบัญชีผู้ใช้ (Custom)
    'staff',         # ระบบจัดการเจ้าหน้าที่
    'announcements', # ระบบประกาศข่าวสาร
    'audit',         # ระบบบันทึกประวัติ (Audit Log)
    'core',          # หน้าหลักและโครงสร้างพื้นฐาน
    'dashboard',     # ระบบกระดานสรุปข้อมูล (ถ้ามี)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls' # ไฟล์หลักที่จัดการเส้นทาง (URL) ทั้งหมดของเว็บ

# ตั้งค่าให้ระบบใช้ UnifiedUser (จาก accounts app) เป็นบัญชีผู้ใช้หลักแทน User มาตรฐานของ Django
AUTH_USER_MODEL = 'accounts.UnifiedUser'

# เส้นทาง URL ที่เกี่ยวข้องกับการล็อกอิน
LOGIN_URL = 'accounts:login'                 # หน้าล็อกอิน
LOGIN_REDIRECT_URL = 'accounts:role_redirect' # ล็อกอินเสร็จให้ไปไหน (ไปเช็ค Role)
LOGOUT_REDIRECT_URL = 'accounts:login'       # ล็อกเอาต์เสร็จให้ไปไหน

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# การตั้งค่าฐานข้อมูล (Database)
# ปัจจุบันใช้ SQLite3 (ฐานข้อมูลแบบไฟล์เดียว) เหมาะสำหรับรันพัฒนาในเครื่อง
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
