# Generated by Django 6.0.7 on 2026-09-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('target_audience', models.CharField(choices=[('ALL', 'All'), ('STUDENT', 'Student'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='ALL', max_length=15)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='announcements/covers/')),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='announcements.announcementcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_announcements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='announcements.campusannouncement')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.campusannouncement')),
            ],
        ),
        migrations.AddIndex(
            model_name='campusannouncement',
            index=models.Index(fields=['status', 'is_deleted'], name='announcemen_status_363ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='campusannouncement',
            index=models.Index(fields=['publish_at'], name='announcemen_publish_34a622_idx'),
        ),
        migrations.AddIndex(
            model_name='campusannouncement',
            index=models.Index(fields=['expire_at'], name='announcemen_expire__0ebc64_idx'),
        ),
        migrations.AddIndex(
            model_name='campusannouncement',
            index=models.Index(fields=['category'], name='announcemen_categor_54fab1_idx'),
        ),
        migrations.AddIndex(
            model_name='campusannouncement',
            index=models.Index(fields=['is_pinned'], name='announcemen_is_pinn_69049f_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read'),
        ),
    ]
